import { GoogleGenerativeAI } from '@google/generative-ai';
import { generateImagePrompt } from './imagePromptGenerator';

const apiKey = process.env.GEMINI_API_KEY;

if (!apiKey) {
  throw new Error('GEMINI_API_KEY must be set in environment variables');
}

const genAI = new GoogleGenerativeAI(apiKey);

/**
 * Генерация изображения через Gemini 3 Pro Image Preview
 * @param offer - Заголовок креатива
 * @param bullets - Буллеты
 * @param profits - Выгода
 * @param cta - Call-to-action
 * @param userPrompt4 - Пользовательский промпт для стилизации изображения (PROMPT4)
 * @param styleId - Выбранный стиль креатива
 * @param referenceImage - Референсное изображение (base64 или URL)
 * @param referenceImageType - Тип изображения ('base64' или 'url')
 * @param referenceImagePrompt - Описание того, как использовать референсное изображение
 * @returns Base64 изображение
 */
export async function generateCreativeImage(
  offer: string,
  bullets: string,
  profits: string,
  cta: string,
  userPrompt4: string,
  styleId: 'modern_performance' | 'live_ugc' | 'visual_hook',
  referenceImage?: string,
  referenceImageType?: 'base64' | 'url',
  referenceImagePrompt?: string
): Promise<string> {
  try {
    const hasReferenceImage = !!referenceImage;

    console.log('[Gemini] Generating image prompt via LLM agent...');
    console.log('[Gemini] Style:', styleId);
    console.log('[Gemini] PROMPT4 length:', userPrompt4.length);

    // Генерируем промпт через LLM-агент
    const prompt = await generateImagePrompt(
      userPrompt4,
      styleId,
      offer,
      bullets,
      profits,
      cta
    );

    // Если есть reference_image_prompt, добавляем его к промпту
    const finalPrompt = referenceImagePrompt 
      ? `${prompt}\n\nДОПОЛНИТЕЛЬНО: ${referenceImagePrompt}`
      : prompt;

    console.log('[Gemini] Generating creative image with Gemini 3 Pro Image Preview...');
    console.log('[Gemini] Final image prompt length:', finalPrompt.length);
    console.log('[Gemini] Has reference image:', hasReferenceImage);

    // Используем Gemini 3 Pro Image Preview для генерации изображений
    const model = genAI.getGenerativeModel({ 
      model: 'gemini-3-pro-image-preview'
    });

    // Формируем массив частей контента
    const contentParts: any[] = [];

    // Добавляем текстовый промпт
    contentParts.push({ text: finalPrompt });

    // Добавляем референсное изображение, если оно есть
    if (referenceImage) {
      if (referenceImageType === 'url') {
        // Если URL, скачиваем изображение
        console.log('[Gemini] Fetching reference image from URL...');
        const response = await fetch(referenceImage);
        const buffer = await response.arrayBuffer();
        const base64 = Buffer.from(buffer).toString('base64');
        
        contentParts.push({
          inlineData: {
            mimeType: response.headers.get('content-type') || 'image/jpeg',
            data: base64
          }
        });
        console.log('[Gemini] Reference image fetched and added');
      } else {
        // Если уже base64
        contentParts.push({
          inlineData: {
            mimeType: 'image/jpeg',
            data: referenceImage
          }
        });
        console.log('[Gemini] Reference image (base64) added');
      }
    }

    const result = await model.generateContent(contentParts);
    const response = result.response;

    // Gemini возвращает изображение в base64
    if (!response.candidates || response.candidates.length === 0) {
      throw new Error('No image generated by Gemini');
    }

    const candidate = response.candidates[0];
    
    // Извлекаем изображение из ответа
    if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
      throw new Error('No image parts in response');
    }

    const imagePart = candidate.content.parts.find((part: any) => part.inlineData);
    
    if (!imagePart || !imagePart.inlineData || !imagePart.inlineData.data) {
      throw new Error('No image data in response');
    }

    const base64Image = imagePart.inlineData.data;

    console.log('[Gemini] Creative image generated successfully');
    console.log('[Gemini] Image size:', base64Image.length, 'bytes (base64)');
    
    return base64Image;
  } catch (error: any) {
    console.error('[Gemini] Error generating creative image:', error);
    throw new Error(`Gemini image generation failed: ${error.message}`);
  }
}

/**
 * Инициализация и проверка доступности Gemini API
 */
export async function initializeGeminiImageAPI(): Promise<void> {
  try {
    console.log('[Gemini Image] Initializing API...');
    console.log('[Gemini Image] Model: gemini-3-pro-image-preview');
    console.log('[Gemini Image] API initialized successfully');
  } catch (error: any) {
    console.error('[Gemini Image] Failed to initialize API:', error);
    throw new Error(`Gemini Image API initialization failed: ${error.message}`);
  }
}

