import { GoogleGenerativeAI } from '@google/generative-ai';
import { generateImagePrompt } from './imagePromptGenerator';

let genAI: GoogleGenerativeAI | null = null;

function getGeminiClient(): GoogleGenerativeAI {
  if (!genAI) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY must be set in environment variables');
    }
    genAI = new GoogleGenerativeAI(apiKey);
  }
  return genAI;
}

/**
 * Генерация изображения через Gemini 3 Pro Image Preview
 * @param offer - Заголовок креатива
 * @param bullets - Буллеты
 * @param profits - Выгода
 * @param cta - Call-to-action
 * @param userPrompt4 - Пользовательский промпт для стилизации изображения (PROMPT4)
 * @param styleId - Выбранный стиль креатива
 * @param referenceImage - Референсное изображение (base64 или URL)
 * @param referenceImageType - Тип изображения ('base64' или 'url')
 * @param referenceImagePrompt - Описание того, как использовать референсное изображение
 * @returns Base64 изображение
 */
export async function generateCreativeImage(
  offer: string,
  bullets: string,
  profits: string,
  cta: string,
  userPrompt4: string,
  styleId: 'modern_performance' | 'live_ugc' | 'visual_hook' | 'premium_minimal' | 'product_hero',
  referenceImage?: string,
  referenceImageType?: 'base64' | 'url',
  referenceImagePrompt?: string
): Promise<string> {
  try {
    const hasReferenceImage = !!referenceImage;

    console.log('[Gemini] Generating image prompt via LLM agent...');
    console.log('[Gemini] Style:', styleId);
    console.log('[Gemini] PROMPT4 length:', userPrompt4.length);

    // Генерируем промпт через LLM-агент
    const prompt = await generateImagePrompt(
      userPrompt4,
      styleId,
      offer,
      bullets,
      profits,
      cta
    );

    // Если есть reference_image_prompt, добавляем его к промпту
    const finalPrompt = referenceImagePrompt 
      ? `${prompt}\n\nДОПОЛНИТЕЛЬНО: ${referenceImagePrompt}`
      : prompt;

    console.log('[Gemini] Generating creative image with Gemini 3 Pro Image Preview...');
    console.log('[Gemini] Final image prompt length:', finalPrompt.length);
    console.log('[Gemini] Has reference image:', hasReferenceImage);

    // Используем Gemini 3 Pro Image Preview для генерации изображений
    const client = getGeminiClient();
    const model = client.getGenerativeModel({
      model: 'gemini-3-pro-image-preview'
    });

    // Формируем массив частей контента
    const contentParts: any[] = [];

    // Добавляем текстовый промпт
    contentParts.push({ text: finalPrompt });

    // Добавляем референсное изображение, если оно есть
    if (referenceImage) {
      if (referenceImageType === 'url') {
        // Если URL, скачиваем изображение
        console.log('[Gemini] Fetching reference image from URL...');
        const response = await fetch(referenceImage);
        const buffer = await response.arrayBuffer();
        const base64 = Buffer.from(buffer).toString('base64');

        contentParts.push({
          inlineData: {
            mimeType: response.headers.get('content-type') || 'image/jpeg',
            data: base64
          }
        });
        console.log('[Gemini] Reference image fetched and added');
      } else {
        // Если уже base64
        contentParts.push({
          inlineData: {
            mimeType: 'image/jpeg',
            data: referenceImage
          }
        });
        console.log('[Gemini] Reference image (base64) added');
      }
    }

    // Конфигурация для генерации в формате 9:16 для Instagram Reels/Stories
    // Используем 2K для preview, позже можно будет upscale до 4K
    const generationConfig = {
      responseModalities: ['IMAGE'],
      imageConfig: {
        aspectRatio: '9:16',
        imageSize: '2K'
      },
      temperature: 1.0,
      topK: 40,
      topP: 0.95
    };

    console.log('[Gemini] Image config: 9:16 aspect ratio, 2K resolution');

    const result = await model.generateContent({
      contents: [{ role: 'user', parts: contentParts }],
      generationConfig
    });
    const response = result.response;

    // Gemini возвращает изображение в base64
    if (!response.candidates || response.candidates.length === 0) {
      throw new Error('No image generated by Gemini');
    }

    const candidate = response.candidates[0];
    
    // Извлекаем изображение из ответа
    if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
      throw new Error('No image parts in response');
    }

    const imagePart = candidate.content.parts.find((part: any) => part.inlineData);
    
    if (!imagePart || !imagePart.inlineData || !imagePart.inlineData.data) {
      throw new Error('No image data in response');
    }

    const base64Image = imagePart.inlineData.data;

    console.log('[Gemini] Creative image generated successfully');
    console.log('[Gemini] Image size:', base64Image.length, 'bytes (base64)');
    
    return base64Image;
  } catch (error: any) {
    console.error('[Gemini] Error generating creative image:', error);
    throw new Error(`Gemini image generation failed: ${error.message}`);
  }
}

/**
 * Upscale изображения с 2K до 4K
 * Используется перед финальным сохранением/скачиванием
 * @param base64Image - Исходное изображение в base64
 * @param originalPrompt - Оригинальный промпт для сохранения стиля
 * @returns Base64 изображение в 4K качестве
 */
export async function upscaleImageTo4K(
  base64Image: string,
  originalPrompt: string,
  aspectRatio: '9:16' | '4:5' = '9:16' // Дефолт для одиночных креативов
): Promise<string> {
  try {
    console.log('[Gemini Upscale] Starting image upscale to 4K...');
    console.log('[Gemini Upscale] Aspect ratio:', aspectRatio);

    const client = getGeminiClient();
    const model = client.getGenerativeModel({
      model: 'gemini-3-pro-image-preview'
    });

    // Формируем контент с исходным изображением
    const contentParts: any[] = [
      {
        text: `${originalPrompt}\n\nУлучши качество этого изображения, сохранив все детали, композицию и стиль без изменений.`
      },
      {
        inlineData: {
          mimeType: 'image/jpeg',
          data: base64Image
        }
      }
    ];

    // Конфигурация для 4K
    const generationConfig = {
      responseModalities: ['IMAGE'],
      imageConfig: {
        aspectRatio: aspectRatio,
        imageSize: '4K'
      },
      temperature: 0.1, // Низкая температура для точного воспроизведения
      topK: 10,
      topP: 0.8
    };

    console.log('[Gemini Upscale] Generating 4K version...');

    const result = await model.generateContent({
      contents: [{ role: 'user', parts: contentParts }],
      generationConfig
    });

    const response = result.response;

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error('No image generated during upscale');
    }

    const candidate = response.candidates[0];

    if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
      throw new Error('No image parts in upscale response');
    }

    const imagePart = candidate.content.parts.find((part: any) => part.inlineData);

    if (!imagePart || !imagePart.inlineData || !imagePart.inlineData.data) {
      throw new Error('No image data in upscale response');
    }

    const upscaledImage = imagePart.inlineData.data;

    console.log('[Gemini Upscale] 4K image generated successfully');
    console.log('[Gemini Upscale] Image size:', upscaledImage.length, 'bytes (base64)');

    return upscaledImage;
  } catch (error: any) {
    console.error('[Gemini Upscale] Error upscaling image:', error);
    throw new Error(`Image upscale failed: ${error.message}`);
  }
}

/**
 * Адаптация изображения под другой aspect ratio
 * Используется для создания 4:5 версии из 9:16 для Feed плейсментов
 * @param base64Image - Исходное изображение в base64 (9:16)
 * @param originalPrompt - Оригинальный промпт для сохранения стиля
 * @param targetAspectRatio - Целевое соотношение сторон
 * @returns Base64 изображение в 4K с новым aspect ratio
 */
export async function adaptImageToAspectRatio(
  base64Image: string,
  originalPrompt: string,
  targetAspectRatio: '4:5' | '1:1' = '4:5'
): Promise<string> {
  try {
    console.log('[Gemini Adapt] Starting image adaptation to', targetAspectRatio);

    const client = getGeminiClient();
    const model = client.getGenerativeModel({
      model: 'gemini-3-pro-image-preview'
    });

    // Промпт для адаптации - просим сохранить контент и стиль
    const adaptPrompt = `${originalPrompt}

ЗАДАЧА: Адаптируй это изображение под формат ${targetAspectRatio}, сохранив:
- Основной контент и композицию
- Цветовую гамму и стиль
- Все важные элементы (текст, объекты, людей)

Расширь или перекомпонуй изображение так, чтобы оно органично смотрелось в новом формате.`;

    const contentParts: any[] = [
      { text: adaptPrompt },
      {
        inlineData: {
          mimeType: 'image/jpeg',
          data: base64Image
        }
      }
    ];

    // Конфигурация для 4K с новым aspect ratio
    const generationConfig = {
      responseModalities: ['IMAGE'],
      imageConfig: {
        aspectRatio: targetAspectRatio,
        imageSize: '4K'
      },
      temperature: 0.3, // Немного выше чем upscale, т.к. нужна адаптация
      topK: 20,
      topP: 0.85
    };

    console.log('[Gemini Adapt] Generating adapted version...');

    const result = await model.generateContent({
      contents: [{ role: 'user', parts: contentParts }],
      generationConfig
    });

    const response = result.response;

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error('No image generated during adaptation');
    }

    const candidate = response.candidates[0];

    if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
      throw new Error('No image parts in adaptation response');
    }

    const imagePart = candidate.content.parts.find((part: any) => part.inlineData);

    if (!imagePart || !imagePart.inlineData || !imagePart.inlineData.data) {
      throw new Error('No image data in adaptation response');
    }

    const adaptedImage = imagePart.inlineData.data;

    console.log('[Gemini Adapt] Adapted image generated successfully');
    console.log('[Gemini Adapt] Target aspect ratio:', targetAspectRatio);
    console.log('[Gemini Adapt] Image size:', adaptedImage.length, 'bytes (base64)');

    return adaptedImage;
  } catch (error: any) {
    console.error('[Gemini Adapt] Error adapting image:', error);
    throw new Error(`Image adaptation failed: ${error.message}`);
  }
}

/**
 * Инициализация и проверка доступности Gemini API
 */
export async function initializeGeminiImageAPI(): Promise<void> {
  try {
    console.log('[Gemini Image] Initializing API...');
    console.log('[Gemini Image] Model: gemini-3-pro-image-preview');
    console.log('[Gemini Image] API initialized successfully');
  } catch (error: any) {
    console.error('[Gemini Image] Failed to initialize API:', error);
    throw new Error(`Gemini Image API initialization failed: ${error.message}`);
  }
}

