import { GoogleGenerativeAI } from '@google/generative-ai';
import { generateCarouselCardPrompt } from './carouselPromptGenerator';
import { upscaleImageTo4K } from './gemini-image';
import { CarouselVisualStyle } from '../types';

let genAI: GoogleGenerativeAI | null = null;

function getGeminiClient(): GoogleGenerativeAI {
  if (!genAI) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY must be set in environment variables');
    }
    genAI = new GoogleGenerativeAI(apiKey);
  }
  return genAI;
}

/**
 * Генерирует одну карточку карусели
 * @param cardText - Текст для карточки
 * @param cardIndex - Индекс карточки (0-based)
 * @param totalCards - Общее количество карточек
 * @param userPrompt1 - PROMPT1 пользователя
 * @param visualStyle - Визуальный стиль карусели
 * @param customPrompt - Дополнительный промпт от пользователя (опционально)
 * @param referenceImages - Массив референсных изображений для передачи в Gemini (base64)
 * @returns Base64 изображение
 */
async function generateCarouselCard(
  cardText: string,
  cardIndex: number,
  totalCards: number,
  userPrompt1: string,
  visualStyle: CarouselVisualStyle,
  customPrompt?: string,
  referenceImages?: string[]
): Promise<string> {
  try {
    console.log(`[Gemini Carousel] Generating card ${cardIndex + 1}/${totalCards}...`);

    // Генерируем промпт через LLM-агент
    const prompt = await generateCarouselCardPrompt(
      userPrompt1,
      cardText,
      cardIndex,
      totalCards,
      visualStyle,
      customPrompt
    );

    console.log('[Gemini Carousel] Generated prompt length:', prompt.length);
    console.log('[Gemini Carousel] Reference images count:', referenceImages?.length || 0);

    const client = getGeminiClient();
    const model = client.getGenerativeModel({
      model: 'gemini-3-pro-image-preview'
    });

    // Формируем массив частей контента
    const contentParts: any[] = [];

    // Добавляем текстовый промпт
    contentParts.push({ text: prompt });

    // Добавляем референсные изображения (если есть)
    if (referenceImages && referenceImages.length > 0) {
      console.log(`[Gemini Carousel] Adding ${referenceImages.length} reference image(s)...`);

      for (const refImage of referenceImages) {
        contentParts.push({
          inlineData: {
            mimeType: 'image/jpeg',
            data: refImage
          }
        });
      }
    }

    // Конфигурация для генерации в формате 4:5 для Instagram карусели
    const generationConfig = {
      responseModalities: ['IMAGE'],
      imageConfig: {
        aspectRatio: '4:5',
        imageSize: '2K'
      },
      temperature: 1.0,
      topK: 40,
      topP: 0.95
    };

    console.log('[Gemini Carousel] Calling Gemini API...');

    const result = await model.generateContent({
      contents: [{ role: 'user', parts: contentParts }],
      generationConfig
    });

    const response = result.response;

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error('No image generated by Gemini');
    }

    const candidate = response.candidates[0];

    if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
      throw new Error('No image parts in response');
    }

    const imagePart = candidate.content.parts.find((part: any) => part.inlineData);

    if (!imagePart || !imagePart.inlineData || !imagePart.inlineData.data) {
      throw new Error('No image data in response');
    }

    const base64Image = imagePart.inlineData.data;

    console.log(`[Gemini Carousel] Card ${cardIndex + 1}/${totalCards} generated successfully`);
    console.log('[Gemini Carousel] Image size:', base64Image.length, 'bytes (base64)');

    return base64Image;

  } catch (error: any) {
    console.error(`[Gemini Carousel] Error generating card ${cardIndex + 1}:`, error);
    throw new Error(`Carousel card generation failed: ${error.message}`);
  }
}

/**
 * Генерирует все карточки карусели последовательно
 * Стратегия:
 * 1. Генерируем 1-ю карточку (без референсов)
 * 2. Генерируем 2-ю карточку (передаем 1-ю как референс)
 * 3. Генерируем остальные карточки (передаем 2-ю как референс для консистентности)
 *
 * @param carouselTexts - Массив текстов для карточек
 * @param userPrompt1 - PROMPT1 пользователя
 * @param visualStyle - Визуальный стиль карусели (по умолчанию 'clean_minimal')
 * @param customPrompts - Опциональные кастомные промпты для каждой карточки
 * @param referenceImages - Опциональные референсные изображения для каждой карточки (base64)
 * @returns Массив base64 изображений
 */
export async function generateCarouselImages(
  carouselTexts: string[],
  userPrompt1: string,
  visualStyle: CarouselVisualStyle = 'clean_minimal',
  customPrompts?: (string | null)[],
  referenceImages?: (string | null)[]
): Promise<string[]> {
  try {
    console.log('[Gemini Carousel] Starting carousel generation...');
    console.log('[Gemini Carousel] Total cards:', carouselTexts.length);

    const generatedImages: string[] = [];
    const totalCards = carouselTexts.length;

    // Определяем основной пользовательский референс (если есть хоть одно изображение в массиве)
    const mainUserReference = referenceImages?.find(img => img !== null) || null;

    for (let i = 0; i < totalCards; i++) {
      const cardText = carouselTexts[i];
      const customPrompt = customPrompts?.[i] || undefined;

      // Собираем referencer изображения для этой карточки
      const cardReferenceImages: string[] = [];

      // КРИТИЧЕСКИ ВАЖНО: Если пользователь предоставил референсное изображение,
      // оно должно быть добавлено к КАЖДОЙ карточке для поддержания консистентности персонажа
      if (mainUserReference) {
        cardReferenceImages.push(mainUserReference);
      }

      // Стратегия консистентности:
      // - Карточка 0 (первая): только пользовательский референс (если есть)
      // - Карточка 1 (вторая): пользовательский референс + карточка 0 как референс стиля
      // - Карточки 2+ (остальные): пользовательский референс + карточка 1 как референс стиля
      if (i === 1 && generatedImages.length >= 1) {
        // Вторая карточка: добавляем первую сгенерированную как референс
        cardReferenceImages.push(generatedImages[0]);
      } else if (i >= 2 && generatedImages.length >= 2) {
        // Третья и последующие: добавляем вторую сгенерированную как референс
        cardReferenceImages.push(generatedImages[1]);
      }

      const image = await generateCarouselCard(
        cardText,
        i,
        totalCards,
        userPrompt1,
        visualStyle,
        customPrompt,
        cardReferenceImages.length > 0 ? cardReferenceImages : undefined
      );

      generatedImages.push(image);

      // Небольшая пауза между генерациями, чтобы не перегрузить API
      if (i < totalCards - 1) {
        await new Promise(resolve => setTimeout(resolve, 1000));
      }
    }

    console.log('[Gemini Carousel] All cards generated successfully');
    return generatedImages;

  } catch (error: any) {
    console.error('[Gemini Carousel] Error generating carousel:', error);
    throw new Error(`Carousel generation failed: ${error.message}`);
  }
}

/**
 * Перегенерирует одну карточку в существующей карусели
 * @param cardText - Текст для карточки
 * @param cardIndex - Индекс карточки (0-based)
 * @param existingImages - Существующие изображения карусели (base64)
 * @param userPrompt1 - PROMPT1 пользователя
 * @param visualStyle - Визуальный стиль карусели (по умолчанию 'clean_minimal')
 * @param customPrompt - Дополнительный промпт от пользователя
 * @param userReferenceImage - Дополнительное референсное изображение от пользователя (base64)
 * @returns Base64 изображение
 */
export async function regenerateCarouselCard(
  cardText: string,
  cardIndex: number,
  existingImages: string[],
  userPrompt1: string,
  visualStyle: CarouselVisualStyle = 'clean_minimal',
  customPrompt?: string,
  userReferenceImage?: string
): Promise<string> {
  try {
    console.log(`[Gemini Carousel] Regenerating card ${cardIndex + 1}...`);

    const totalCards = existingImages.length;
    const cardReferenceImages: string[] = [];

    // Если пользователь прикрепил свое изображение, добавляем его
    if (userReferenceImage) {
      cardReferenceImages.push(userReferenceImage);
    }

    // Для консистентности используем вторую карточку как референс (если она есть и это не сама вторая карточка)
    if (cardIndex !== 1 && existingImages.length >= 2) {
      cardReferenceImages.push(existingImages[1]);
    }
    // Если регенерируем вторую карточку, используем первую
    else if (cardIndex === 1 && existingImages.length >= 1) {
      cardReferenceImages.push(existingImages[0]);
    }

    const image = await generateCarouselCard(
      cardText,
      cardIndex,
      totalCards,
      userPrompt1,
      visualStyle,
      customPrompt,
      cardReferenceImages.length > 0 ? cardReferenceImages : undefined
    );

    console.log(`[Gemini Carousel] Card ${cardIndex + 1} regenerated successfully`);
    return image;

  } catch (error: any) {
    console.error(`[Gemini Carousel] Error regenerating card ${cardIndex + 1}:`, error);
    throw new Error(`Card regeneration failed: ${error.message}`);
  }
}

/**
 * Upscale всех карточек карусели до 4K
 * @param images - Массив изображений в 2K (base64)
 * @param prompts - Массив промптов, использованных для генерации (для сохранения стиля)
 * @returns Массив upscaled изображений в 4K (base64)
 */
export async function upscaleCarouselTo4K(
  images: string[],
  prompts: string[]
): Promise<string[]> {
  try {
    console.log('[Gemini Carousel Upscale] Starting upscale to 4K...');
    console.log('[Gemini Carousel Upscale] Total images:', images.length);

    const upscaledImages: string[] = [];

    for (let i = 0; i < images.length; i++) {
      console.log(`[Gemini Carousel Upscale] Upscaling image ${i + 1}/${images.length}...`);

      const upscaledImage = await upscaleImageTo4K(
        images[i],
        prompts[i] || 'Premium минималистичный рекламный креатив',
        '4:5' // Карусель всегда в формате 4:5
      );

      upscaledImages.push(upscaledImage);

      // Пауза между upscale
      if (i < images.length - 1) {
        await new Promise(resolve => setTimeout(resolve, 1000));
      }
    }

    console.log('[Gemini Carousel Upscale] All images upscaled successfully');
    return upscaledImages;

  } catch (error: any) {
    console.error('[Gemini Carousel Upscale] Error upscaling carousel:', error);
    throw new Error(`Carousel upscale failed: ${error.message}`);
  }
}
