server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      # Шаг 1: Распарсить Docker JSON обёртку (извлекает поле "log")
      - docker: {}
      
      # Шаг 2: Распарсить Pino JSON внутри поля "log"
      - json:
          expressions:
            level:
            message:
            service:
            environment:
            module:
            userAccountId:
            userAccountName:
            userTelegram:
            msg:
            time:
      
      # Шаг 3: Преобразовать поля в labels для индексации
      - labels:
          level:
          service:
          environment:
          module:
          userAccountId:
          userAccountName:
          userTelegram:
          msg:
      
      # Шаг 4: Использовать time из Pino как timestamp
      - timestamp:
          source: time
          format: RFC3339Nano
