server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_id']
        regex: (.*)
        target_label: '__path__'
        replacement: '/var/lib/docker/containers/$1/$1-json.log'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'
      - replacement: 'docker-logs'
        target_label: 'job'
    pipeline_stages:
      # Шаг 1: Распарсить Docker JSON обёртку (извлекает поле "log" и timestamp)
      - docker: {}
      
      # Шаг 2: Распарсить Pino JSON внутри поля "log"
      - json:
          expressions:
            level:
            service:
            msg:
            userAccountId:
            userAccountName:
            environment:
            module:
      
      # Шаг 3: Преобразовать поля в labels для индексации
      - labels:
          level:
          service:
          msg:
          userAccountId:
          userAccountName:
          environment:
          module:
