-- Migration: Add flexible lead_tags system
-- Date: 2025-11-12
-- Description: Add lead_tags JSONB field and deprecate rigid B2B-specific fields

-- Add lead_tags column for flexible tagging
ALTER TABLE dialog_analysis 
ADD COLUMN IF NOT EXISTS lead_tags JSONB DEFAULT '[]'::jsonb;

-- Create GIN index for efficient tag searching
CREATE INDEX IF NOT EXISTS idx_dialog_analysis_lead_tags 
ON dialog_analysis USING GIN (lead_tags);

-- Add comment for documentation
COMMENT ON COLUMN dialog_analysis.lead_tags IS 
'Flexible tags generated by LLM: geography, budget, urgency, interests, problems, categories, etc. Examples: ["Москва", "Срочно"], ["Интересуется отбеливанием"], ["Бюджет 50-100к"]';

-- Note: We are keeping business_type, is_medical, is_owner, uses_ads_now for backward compatibility
-- but they will not be used in the new UI




